name: Deploy to Production
on:
  push:
    branches:
      - main # main
  workflow_dispatch:
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  build: 
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output script file name
        run: | 
          echo "Script file name: ${{ needs.build.outputs.script-file }}" >> $GITHUB_OUTPUT
      - name: Deploy project
        run: echo "Deploying..."